### ISSUE TITLE
sodium_memzero issue in PHP 7.2+

### ISSUE THREAD

**Issue by UVLabs** [dwgebler/php-encryption#3]
I'm running into a "strange" issue. Which I don't quite understand. 

Currently I'm trying to make use of the `encryptWithSecret()` method to encrypt a piece of data. The thing is it's failing due to the `sodium_memzero()` lines you have here: https://github.com/dwgebler/php-encryption/blob/master/src/Encryption.php#L69-L71

When I output the `SodiumException` error this is what it says:

`This is not implemented in sodium_compat, as it is not possible to securely wipe memory from PHP. To fix this error, make sure libsodium is installed and the PHP extension is enabled.`

-- 

The thing is that seems to be an error that comes from a `sodium_compat` library: https://github.com/paragonie/sodium_compat/blob/v1.12.1/src/Compat.php#L3210 but since sodium is included by default in PHP 7.2+ I don't know why I'd be getting this exception?

I did some googling and found these this thread: https://github.com/phpseclib/phpseclib/issues/1432 and this fix: https://github.com/phpseclib/phpseclib/commit/e3557220d7b4f10b4b8420ba71845e88b3b69c50 for that particular library. But this is for PHP <7.2 so why would I be getting that exception on PHP 8 which supposed to have its own included version of sodium with no need for a compat library?

Currently the fix seems to be to instead use `unset` rather than `sodium_memzero`

**Comment by dwgebler** [comment]
This occurs when you don't have Sodium extension installed and are using `sodium_compat` as a polyfill. It is still possible to run newer versions of PHP without Sodium; you can run `php -m` to check what extensions you have installed.
